[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv

lib_deps = 
    lvgl/lvgl@^8.3.11
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson@^7.0.4
    h2zero/NimBLE-Arduino@^2.1.2  ; Updated to v2+ to fix the NimBLEConnInfo override errors

build_flags = 
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D LV_CONF_SKIP               
    -D LV_COLOR_DEPTH=16          
    -D TOUCH_CS=32                
    -D LV_FONT_MONTSERRAT_20=1
    -D LV_FONT_MONTSERRAT_24=1
    -D LV_FONT_MONTSERRAT_36=1