#ifndef CALIBRATION_APP_H
#define CALIBRATION_APP_H

#include <lvgl.h>
#include "ui.h" // Gives access to ui_ScreenCalibrate (or ui_Calibrate)

extern AppState currentApp;
extern void save_calibration_to_preferences(); // Bridge to your save logic

bool calibrationScreenLoaded = false;

void run_calibration_app() {
    // 1. Load the calibration screen on first entry
    if (!calibrationScreenLoaded) {
        // Ensure this matches the exact screen object name generated by SquareLine
        lv_disp_load_scr(ui_Calibrate); 
        calibrationScreenLoaded = true;
    }

    // 2. Keep LVGL ticking so touch controls and sliders work smoothly
    lv_tick_inc(5); 
    lv_timer_handler(); 

    // Note: In SquareLine Studio, make sure your "Back" or "Save" button 
    // on the calibration screen has an event attached that triggers a function 
    // setting: currentApp = APP_HOME; calibrationScreenLoaded = false;
}

#endif